# Generated by Django 5.2.9 on 2025-12-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=99, null=True)),
                ('last_name', models.CharField(blank=True, max_length=99, null=True)),
                ('phone_number', models.CharField(max_length=99, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('age', models.IntegerField(default=0)),
                ('course', models.CharField(choices=[('1-course', '1-course'), ('2-course', '2-course'), ('3-course', '3-course'), ('4-course', '4-course')], max_length=15)),
                ('picture', models.ImageField(upload_to='')),
                ('is_finished', models.BooleanField(default=False)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_ad', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
